### ISSUE TITLE
MailgunTransport is not a constructor

### ISSUE THREAD

**Issue by leviwheatcroft** [xr0master/mailgun-nodemailer-transport#2]
importing this module as described in the readme will generate a typeerror: `MailgunTransport is not a constructor`.

[this](https://github.com/xr0master/mailgun-nodemailer-transport/blob/master/src/MailgunTransport.ts#L21) export will generate an export object like `{ MailgunTransport }` so you'd need to consume it like this:

```
const { MailgunTransporter } = require('mailgun-nodemailer-transport')
```

Would making the class the default export work? A la `export default class MailgunTransport...`

**Comment by xr0master** [comment]
Hey. Thank you for your feedback.
It's easy to fix it, but can I ask why you prefer that kind of syntax?

**Comment by leviwheatcroft** [comment]
it's not just my preference.

The readme suggests usage like `const MailgunTransport = require('mailgun-nodemailer-transport');` but if I try that, then when I `new MailgunTransport` I get a TypeError.

Presently, the module needs to be required as `const { MailgunTransporter } = require('mailgun-nodemailer-transport')`

If I remember correctly, if you're using babel you can just `const MailgunTransport = import 'mailgun-nodemailer-transport'` and it will work. Its only those using `require(...)` that will notice this.

**Comment by xr0master** [comment]
You are right. I'll fix it ASAP. Thanks

**Comment by xr0master** [comment]
Added the default export. Closed.
@leviwheatcroft  thank you.
